 file(COPY ${EIGEN3_INCLUDE_DIRS} DESTINATION ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

 file(ARCHIVE_CREATE OUTPUT ${CMAKE_RELEASE_LOCATION}/MSSAMex.7z
    PATHS ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
    FORMAT 7zip
)

#message("${EIGEN3_INCLUDE_DIRS}")

